/**
 * Helper to load the api sidebar JSON only if it exists
 * returns empty array otherwise
 */
function loadApiSidebarIfExists() {
    try {
        return require("./docs/api/sidebar.json")
    } catch {
        return []
    }
}

/**
 * Helper to load the rest sidebar js only if it exists
 * returns empty other array otherwise
 */
function loadRestSidebarIfExists() {
    try {
        return require("./docs/rest/login-service/sidebar.js")
    } catch {
        return []
    }
}

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
    docSidebar: [{ type: "autogenerated", dirName: "docs" }],
    apiSidebar: loadApiSidebarIfExists(),
    graphqlSidebar: [
        {
            type: "category",
            label: "Public API",
            link: {
                type: "doc",
                id: "graphql/api-public"
            },
            items: [{
                type: "autogenerated",
                dirName: "graphql/api-public"
            }]
        },
        {
            type: "category",
            label: "Internal API",
            link: {
                type: "doc",
                id: "graphql/api-internal"
            },
            items: [{
                type: "autogenerated",
                dirName: "graphql/api-internal"
            }]
        }
    ],
    restSidebar: loadRestSidebarIfExists()
};

module.exports = sidebars;