name: Test deployment

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '42 14 * * 3' # every thursday at 2:42 pm

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build dokkaHtmlMultiModule
      - name: Save graphql schemas
        run: |
          chmod +x ./website/scripts/generate-graphql-schema.sh
          ./website/scripts/generate-graphql-schema.sh
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Install login-service dependencies
        run: ./gradlew login-service:npm_ci
      - name: Save openapi schemas
        run: |
          chmod +x ./website/scripts/generate-openapi-schema.sh
          ./website/scripts/generate-openapi-schema.sh
      - name: Modify Dokka output
        uses: graphglue/dokka-html-mdx-transform@v1.7.10
        with:
          src: "build/dokka/htmlMultiModule"
          modules: |
            core
            api-common
            api-public
            api-internal
            sync
            github
          dest: "website/docs"
          folder: "api"
      - name: Install website dependencies
        run: npm ci
        working-directory: website
      - name: Update graphql documentation
        run: |
          chmod +x ./website/scripts/update-graphql-doc.sh
          ./website/scripts/update-graphql-doc.sh
      - name: Update rest documentation
        run: |
          chmod +x ./website/scripts/update-rest-doc.sh
          ./website/scripts/update-rest-doc.sh
      - name: Build website
        run: npm run build
        working-directory: website